name: PyPI release
run-name: PyPI release ${{ inputs.tag || github.ref }}

on:
  release:
    types:
    - published
  workflow_dispatch:
    inputs:
      tag:
        description: "Existing release tag (see create-release workflow)"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse.outputs.version }}
      name: ${{ steps.parse.outputs.name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Parse tag
        id: parse
        env:
          TAG: ${{ github.event.inputs.tag || github.ref }}
        run: |
          regex="^(.*)_v(.*)$"
          [[ $TAG =~ $regex ]] || exit 1
          name=${BASH_REMATCH[1]}
          version=${BASH_REMATCH[2]}
          echo "name=$name" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Install deps
        run: python -m pip install --upgrade pip setuptools_scm build

      - name: Build
        working-directory: projects/${{ steps.parse.outputs.name }}
        run: python -m build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: projects/${{ steps.parse.outputs.name }}/dist

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/${{ needs.build.outputs.name }}
    permissions:
      id-token: write
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  release-container:
    if: ${{ needs.build.outputs.name == 'fal' }}
    uses: ./.github/workflows/container.yml
    needs: build
    with:
      version: ${{ needs.build.outputs.version }}
